version: "3.7"

services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    #command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

volumes:
  portainer_data:
